server:
  port: 8762

spring:
  application:
    name: eureka-client
  mvc:
    servlet:
      path: /eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck: true
  instance:
    status-page-url-path: ${spring.mvc.servlet.path}/actuator/info
    health-check-url-path: ${spring.mvc.servlet.path}/actuator/health
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
